/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Vishkanya_pujaRouteImport } from './routes/vishkanya_puja'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as IndexRouteImport } from './routes/index'

const Vishkanya_pujaRoute = Vishkanya_pujaRouteImport.update({
  id: '/vishkanya_puja',
  path: '/vishkanya_puja',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/vishkanya_puja': typeof Vishkanya_pujaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/vishkanya_puja': typeof Vishkanya_pujaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/vishkanya_puja': typeof Vishkanya_pujaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/donate' | '/vishkanya_puja'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/donate' | '/vishkanya_puja'
  id: '__root__' | '/' | '/donate' | '/vishkanya_puja'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonateRoute: typeof DonateRoute
  Vishkanya_pujaRoute: typeof Vishkanya_pujaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vishkanya_puja': {
      id: '/vishkanya_puja'
      path: '/vishkanya_puja'
      fullPath: '/vishkanya_puja'
      preLoaderRoute: typeof Vishkanya_pujaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonateRoute: DonateRoute,
  Vishkanya_pujaRoute: Vishkanya_pujaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
